In [2]:
import pandas as pd

In [4]:
data = pd.read_csv(r'C:\Users\rosar\RufoEsEterno\universidad202601\TF-TP_DataVisualization\Data\2025-Gasto-OPDS.csv')

In [5]:
data.head(20)

,ANO_EJE,MES_EJE,GRUPO_ENTIDAD,GRUPO_ENTIDAD_NOMBRE,SEC_EJEC,EJECUTORA,EJECUTORA_NOMBRE,DEPARTAMENTO_EJECUTORA,DEPARTAMENTO_EJECUTORA_NOMBRE,PROVINCIA_EJECUTORA,...,ESPECIFICA_NOMBRE,ESPECIFICA_DET,ESPECIFICA_DET_NOMBRE,MONTO_PIA,MONTO_PIM,MONTO_COMPROMETIDO,MONTO_DEVENGADO,MONTO_GIRADO,MONTO_COMPROMETIDO_ANUAL,MONTO_CERTIFICADO
0,2025,2,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,"SERVICIOS DE ENERGIA ELECTRICA, AGUA Y GAS",1,SERVICIO DE SUMINISTRO DE ENERGIA ELECTRICA,0,0,10799.50,10799.50,10799.50,10799.50,0.00
1,2025,7,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,"COMBUSTIBLES, CARBURANTES, LUBRICANTES Y AFINES",1,COMBUSTIBLES Y CARBURANTES,0,0,0.00,0.00,409.16,0.00,-0.49
2,2025,3,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,"COMBUSTIBLES, CARBURANTES, LUBRICANTES Y AFINES",1,COMBUSTIBLES Y CARBURANTES,0,0,0.00,422.51,0.00,0.00,0.00
3,2025,2,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,DE MAQUINARIAS Y EQUIPOS,1,DE MAQUINARIAS Y EQUIPOS,0,0,0.00,0.00,0.00,5522.40,5522.40
4,2025,9,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,DE MAQUINARIAS Y EQUIPOS,1,DE MAQUINARIAS Y EQUIPOS,0,0,0.00,0.00,16456.00,0.00,0.00
5,2025,10,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,GASTOS VARIABLES Y OCASIONALES,6,COMPENSACION VACACIONAL (VACACIONES TRUNCAS) A...,0,0,0.00,0.00,7591.95,0.00,0.00
6,2025,0,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,LOCACIÓN DE SERVICIOS REALIZADOS POR PERSONA N...,1,LOCACIÓN DE SERVICIOS REALIZADOS POR PERSONA N...,6600,13925,0.00,0.00,0.00,0.00,0.00
7,2025,0,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,COMPRA DE OTROS BIENES,3,"LIBROS, DIARIOS, REVISTAS Y OTROS BIENES IMPRE...",0,3700,0.00,0.00,0.00,0.00,0.00
8,2025,10,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,OTROS SERVICIOS,6,"SERVICIO DE IMPRESIONES, ENCUADERNACION Y EMPA...",0,0,0.00,0.00,0.00,0.00,-720.00
9,2025,8,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,COMPRA DE OTROS BIENES,3,"LIBROS, DIARIOS, REVISTAS Y OTROS BIENES IMPRE...",0,0,1400.00,0.00,0.00,1400.00,1400.00
10,2025,8,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,LOCACIÓN DE SERVICIOS REALIZADOS POR PERSONA N...,1,LOCACIÓN DE SERVICIOS REALIZADOS POR PERSONA N...,0,0,0.00,1130.00,1130.00,0.00,3390.00
11,2025,12,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,OTROS SERVICIOS,6,"SERVICIO DE IMPRESIONES, ENCUADERNACION Y EMPA...",0,0,850.00,0.00,0.00,850.00,850.00
12,2025,1,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,DE OFICINA,2,"PAPELERIA EN GENERAL, UTILES Y MATERIALES DE O...",0,0,0.00,0.00,0.00,200.00,194.70
13,2025,12,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,COMPRA DE OTROS BIENES,99,OTROS BIENES,0,0,0.00,-5.55,-5.55,0.00,0.00
14,2025,6,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,SERVICIOS TÉCNICOS Y PROFESIONALES DESARROLLAD...,98,OTROS SERVICIOS TÉCNICOS Y PROFESIONALES DESAR...,0,0,0.00,0.00,0.00,1540.00,0.00
15,2025,5,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,DE OFICINA,2,"PAPELERIA EN GENERAL, UTILES Y MATERIALES DE O...",0,0,0.00,0.00,0.00,-5.30,0.00
16,2025,12,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,ALQUILERES DE MUEBLES E INMUEBLES,1,DE EDIFICIOS Y ESTRUCTURAS,0,0,1500.00,1500.00,1500.00,1500.00,0.00
17,2025,0,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,"ADQUISICION DE MOBILIARIO, EQUIPOS Y APARATOS ...",2,EQUIPOS,0,49615,0.00,0.00,0.00,0.00,0.00
18,2025,6,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,OBLIGACIONES DEL EMPLEADOR,15,CONTRIBUCIONES A ESSALUD DE CONTRATO ADMINISTR...,0,0,6472.68,6472.68,6472.68,-7110.87,-7110.87
19,2025,10,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,SERVICIOS DE SALUD,1,GASTOS POR PRESTACIONES DE SALUD,0,0,11280.00,11280.00,11280.00,11280.00,3720.00

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65698 entries, 0 to 65697
Data columns (total 58 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ANO_EJE                        65698 non-null  int64
 1   MES_EJE                        65698 non-null  int64
 2   GRUPO_ENTIDAD                  65698 non-null  int64
 3   GRUPO_ENTIDAD_NOMBRE           65698 non-null  object
 4   SEC_EJEC                       65698 non-null  int64
 5   EJECUTORA                      65698 non-null  int64
 6   EJECUTORA_NOMBRE               65698 non-null  object
 7   DEPARTAMENTO_EJECUTORA         65698 non-null  int64
 8   DEPARTAMENTO_EJECUTORA_NOMBRE  65698 non-null  object
 9   PROVINCIA_EJECUTORA            65698 non-null  int64
 10  PROVINCIA_EJECUTORA_NOMBRE     65698 non-null  object
 11  DISTRITO_EJECUTORA             65698 non-null  int64
 12  DISTRITO_EJECUTORA_NOMBRE      65698 non-null  object
 13  SEC_FUNC                       65698 non-null  int64
 14  PROGRAMA_PPTO                  65698 non-null  int64
 15  PROGRAMA_PPTO_NOMBRE           65698 non-null  object
 16  TIPO_ACT_PROY                  65698 non-null  int64
 17  PRODUCTO_PROYECTO              65698 non-null  int64
 18  PRODUCTO_PROYECTO_NOMBRE       65698 non-null  object
 19  ACTIVIDAD_ACCION_OBRA          65698 non-null  int64
 20  ACTIVIDAD_ACCION_OBRA_NOMBRE   65698 non-null  object
 21  FUNCION                        65698 non-null  int64
 22  FUNCION_NOMBRE                 65698 non-null  object
 23  DIVISION_FUNCIONAL             65698 non-null  int64
 24  DIVISION_FUNCIONAL_NOMBRE      65698 non-null  object
 25  GRUPO_FUNCIONAL                65698 non-null  int64
 26  GRUPO_FUNCIONAL_NOMBRE         65698 non-null  object
 27  META                           65698 non-null  int64
 28  FINALIDAD                      65698 non-null  int64
 29  META_NOMBRE                    65698 non-null  object
 30  DEPARTAMENTO_META              65698 non-null  int64
 31  DEPARTAMENTO_META_NOMBRE       65698 non-null  object
 32  FUENTE_FINANCIAMIENTO          65698 non-null  int64
 33  FUENTE_FINANCIAMIENTO_NOMBRE   65698 non-null  object
 34  RUBRO                          65698 non-null  int64
 35  RUBRO_NOMBRE                   65698 non-null  object
 36  TIPO_RECURSO                   65698 non-null  int64
 37  TIPO_RECURSO_NOMBRE            65698 non-null  object
 38  CATEGORIA_GASTO                65698 non-null  int64
 39  CATEGORIA_GASTO_NOMBRE         65698 non-null  object
 40  TIPO_TRANSACCION               65698 non-null  int64
 41  GENERICA                       65698 non-null  int64
 42  GENERICA_NOMBRE                65698 non-null  object
 43  SUBGENERICA                    65698 non-null  int64
 44  SUBGENERICA_NOMBRE             65698 non-null  object
 45  SUBGENERICA_DET                65698 non-null  int64
 46  SUBGENERICA_DET_NOMBRE         65698 non-null  object
 47  ESPECIFICA                     65698 non-null  int64
 48  ESPECIFICA_NOMBRE              65698 non-null  object
 49  ESPECIFICA_DET                 65698 non-null  int64
 50  ESPECIFICA_DET_NOMBRE          65698 non-null  object
 51  MONTO_PIA                      65698 non-null  int64
 52  MONTO_PIM                      65698 non-null  int64
 53  MONTO_COMPROMETIDO             65698 non-null  float64
 54  MONTO_DEVENGADO                65698 non-null  float64
 55  MONTO_GIRADO                   65698 non-null  float64
 56  MONTO_COMPROMETIDO_ANUAL       65698 non-null  float64
 57  MONTO_CERTIFICADO              65698 non-null  float64
dtypes: float64(5), int64(31), object(22)
memory usage: 29.1+ MB

In [7]:
data.sample(10)

,ANO_EJE,MES_EJE,GRUPO_ENTIDAD,GRUPO_ENTIDAD_NOMBRE,SEC_EJEC,EJECUTORA,EJECUTORA_NOMBRE,DEPARTAMENTO_EJECUTORA,DEPARTAMENTO_EJECUTORA_NOMBRE,PROVINCIA_EJECUTORA,...,ESPECIFICA_NOMBRE,ESPECIFICA_DET,ESPECIFICA_DET_NOMBRE,MONTO_PIA,MONTO_PIM,MONTO_COMPROMETIDO,MONTO_DEVENGADO,MONTO_GIRADO,MONTO_COMPROMETIDO_ANUAL,MONTO_CERTIFICADO
26340,2025,5,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500235,0,FONDO METROPOLITANO DE INVERSIONES DE LIMA,15,LIMA,1,...,OTROS GASTOS DIVERSOS DE ACTIVOS NO FINANCIEROS,3,GASTO POR LA CONTRATACION DE SERVICIOS,0,0,0.00,0.00,0.00,38000.00,38000.00
41517,2025,10,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500256,0,SISTEMA METROPOLITANO DE LA SOLIDARIDAD - SISOL,15,LIMA,1,...,CONTRATO ADMINISTRATIVO DE SERVICIOS,1,CONTRATO ADMINISTRATIVO DE SERVICIOS - INDETER...,0,0,3264.19,3257.95,3257.95,0.00,0.00
50570,2025,3,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500256,0,SISTEMA METROPOLITANO DE LA SOLIDARIDAD - SISOL,15,LIMA,1,...,"SERVICIOS DE ENERGIA ELECTRICA, AGUA Y GAS",2,SERVICIO DE AGUA Y DESAGUE,0,0,0.00,1469.00,2903.70,0.00,0.00
3076,2025,4,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,CONTRATO ADMINISTRATIVO DE SERVICIOS,1,CONTRATO ADMINISTRATIVO DE SERVICIOS - INDETER...,0,0,167.59,167.59,167.41,0.00,0.00
32804,2025,12,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500232,0,SERVICIO DE PARQUES DE LIMA,15,LIMA,1,...,OBLIGACIONES DEL EMPLEADOR,15,CONTRIBUCIONES A ESSALUD DE CONTRATO ADMINISTR...,0,0,0.00,0.00,0.00,-0.52,-0.52
29002,2025,7,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500233,0,INSTITUTO CATASTRAL DE LIMA,15,LIMA,1,...,SERVICIOS TÉCNICOS Y PROFESIONALES DESARROLLAD...,98,OTROS SERVICIOS TÉCNICOS Y PROFESIONALES DESAR...,0,0,10000.00,0.00,0.00,0.00,0.00
29565,2025,0,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500231,0,SERVICIO DE ADMINISTRACION TRIBUTARIA DE LIMA,15,LIMA,1,...,CONTRATO ADMINISTRATIVO DE SERVICIOS,2,CONTRATO ADMINISTRATIVO DE SERVICIOS - TRANSIT...,814560,769432,0.00,0.00,0.00,0.00,0.00
38016,2025,8,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500234,0,INSTITUTO METROPOLITANO DE PLANIFICACION,15,LIMA,1,...,OTROS SERVICIOS,6,"SERVICIO DE IMPRESIONES, ENCUADERNACION Y EMPA...",0,0,0.00,0.00,0.00,1112.10,0.00
346,2025,7,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500319,0,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,4,AREQUIPA,1,...,"ADQUISICION DE MOBILIARIO, EQUIPOS Y APARATOS ...",1,MOBILIARIO,0,0,0.00,99.00,99.00,0.00,0.00
31162,2025,0,14,ORGANISMOS PUBLICOS DESCENTRALIZADOS MUNICIPALES,500249,0,AUTORIDAD MUNICIPAL DE PROTECCION DE LOS HUMED...,15,LIMA,1,...,OBLIGACIONES DEL EMPLEADOR,6,OTRAS CONTRIBUCIONES DEL EMPLEADOR,6950,0,0.00,0.00,0.00,0.00,0.00

In [10]:
data["ESPECIFICA_NOMBRE"].value_counts(dropna=False)

ESPECIFICA_NOMBRE
OBLIGACIONES DEL EMPLEADOR                              6016
CONTRATO ADMINISTRATIVO DE SERVICIOS                    5692
OTROS SERVICIOS                                         4899
LOCACIÓN DE SERVICIOS REALIZADOS POR PERSONA NATURAL    3773
VIAJES DOMESTICOS                                       3365
                                                        ...
TRANSFERENCIAS CORRIENTES                                  4
INDEMNIZACIONES Y COMPENSACIONES                           4
FORMACION Y CAPACITACION                                   4
INFRAESTRUCTURA ELECTRICA                                  3
ADQUISICION DE BIENES AGROPECUARIOS, MINEROS Y OTROS       2
Name: count, Length: 96, dtype: int64

In [12]:
data["EJECUTORA_NOMBRE"].unique()

array(['ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU',
       'INSTITUTO MUNICIPAL DE PLANEAMIENTO DE AREQUIPA',
       'SERVICIO MUNICIPAL DE ADMINISTRACIÓN DEL MATADERO METROPOLITANO DE RÍO SECO',
       'ZONA ESPECIAL DE DESARROLLO MATARANI - ZED MATARANI',
       'SERVICIO DE ADMINISTRACIÓN TRIBUTARIA DE HUAMANGA - AYNI MUNICIPAL',
       'TERRAPUERTO MUNICIPAL LIBERTADORES DE AMERICA',
       'SERVICIO DE ADMINISTRACIÓN TRIBUTARIA DE CAJAMARCA',
       'SERVICIO DE ADMINISTRACIÓN TRIBUTARIA DE ICA',
       'SERVICIO DE ADMINISTRACION TRIBUTARIA DE HUANCAYO',
       'TRANSPORTES METROPOLITANOS DE TRUJILLO',
       'SERVICIO DE GESTIÓN AMBIENTAL DE TRUJILLO',
       'SERVICIO DE ADMINISTRACIÓN DE INMUEBLES MUNICIPALES DE TRUJILLO',
       'SERVICIO DE ADMINISTRACION TRIBUTARIA DE TRUJILLO',
       'SERVICIO DE ADMINISTRACIÓN TRIBUTARIA DE CHICLAYO - SATCH',
       'SERVICIO DE ADMINISTRACIÓN TRIBUTARIA DE JOSÉ LEONARDO ORTIZ',
       'FONDO METROPOLITANO DE INVERSIONES DE LIMA',
       'SERVICIO DE ADMINISTRACION TRIBUTARIA DE LIMA',
       'INSTITUTO CATASTRAL DE LIMA',
       'AUTORIDAD MUNICIPAL DE PROTECCION DE LOS HUMEDALES PANTANOS DE VILLA',
       'SERVICIO DE PARQUES DE LIMA',
       'INSTITUTO METROPOLITANO DE PLANIFICACION',
       'AUTORIDAD DEL PROYECTO COSTA VERDE - APCV',
       'HOSPITAL MUNICIPAL DE OLIVOS',
       'SISTEMA METROPOLITANO DE LA SOLIDARIDAD - SISOL',
       'PATRONATO DEL PARQUE DE LAS LEYENDAS',
       'ZONA ESPECIAL DE DESARROLLO ILO - ZED ILO',
       'SERVICIO DE ADMINISTRACION TRIBUTARIA DE PIURA',
       'ZONA ESPECIAL DE DESARROLLO PAITA - ZED PAITA',
       'SERVICIO DE ADMINISTRACION TRIBUTARIA DE SULLANA - SAT SULLANA',
       'SERVICIO DE ADMINISTRACION TRIBUTARIA DE TARAPOTO - SAT TARAPOTO',
       'COMITE DE ADMINISTRACIÓN DE LA ZONA FRANCA Y ZONA COMERCIAL DE TACNA - ZOFRATACNA'],
      dtype=object)